import { createElement } from 'lwc';
import GlobalEventRequest_Internal_ET from 'c/globalEventRequest_Internal_ET';

describe('c-global-event-request-internal-et', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-global-event-request-internal-et', {
            is: GlobalEventRequest_Internal_ET
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});